from django.db import models

class OrdenCompraCabecera(models.Model):
    oc_numero = models.IntegerField(primary_key=True)
    oc_compania = models.CharField(blank=True, null=True)
    oc_agencia = models.CharField(blank=True, null=True)
    oc_division = models.CharField(blank=True, null=True)
    oc_usring = models.CharField(blank=True, null=True)
    oc_fecing = models.CharField()
    oc_solicit = models.CharField(blank=True, null=True)
    oc_estado = models.CharField(blank=True, null=True)
    oc_tipo = models.CharField(blank=True, null=True)
    oc_usraprd = models.CharField(blank=True, null=True)
    oc_fehaprd = models.DateTimeField(blank=True, null=True)
    oc_usraprf = models.CharField(blank=True, null=True)
    oc_fehaprf = models.DateTimeField(blank=True, null=True)
    oc_codpro = models.IntegerField()
    oc_fecent = models.DateField(blank=True, null=True)
    oc_facpro = models.CharField(blank=True, null=True)
    oc_fecfac = models.DateField(blank=True, null=True)
    oc_valfac = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    oc_valcst = models.DecimalField(max_digits=12, decimal_places=2)
    oc_descto = models.DecimalField(max_digits=12, decimal_places=2)
    oc_plazo = models.SmallIntegerField()
    oc_iva_mo = models.SmallIntegerField()
    oc_iva_rp = models.SmallIntegerField(blank=True, null=True)
    oc_recargo = models.SmallIntegerField()
    oc_ordtra = models.IntegerField(blank=True, null=True)
    oc_bodprn = models.CharField(blank=True, null=True)
    oc_obser1 = models.CharField(blank=True, null=True)
    oc_obser2 = models.CharField(blank=True, null=True)
    oc_clasif1 = models.CharField(blank=True, null=True)
    oc_porcret1 = models.DecimalField(max_digits=4, decimal_places=2)
    oc_porcret2 = models.DecimalField(max_digits=4, decimal_places=2)
    oc_moneda = models.CharField(blank=True, null=True)
    oc_atencion = models.CharField(blank=True, null=True)
    oc_cta_aux = models.CharField(blank=True, null=True)
    oc_retiva = models.DecimalField(max_digits=5, decimal_places=2)
    oc_numdia = models.IntegerField(blank=True, null=True)
    oc_cod_tip = models.CharField(blank=True, null=True)
    oc_ide_cre = models.CharField(blank=True, null=True)
    oc_autimp = models.CharField(blank=True, null=True)
    oc_serie = models.CharField(blank=True, null=True)
    oc_aut_sri = models.CharField(blank=True, null=True)
    oc_fec_val = models.DateField(blank=True, null=True)
    oc_cuenta = models.CharField(blank=True, null=True)
    oc_subtipo = models.CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ocxxt001'
        unique_together = (('oc_compania', 'oc_division', 'oc_numero', 'oc_agencia'),)