from django.db import models

class Proveedor(models.Model):
    pv_cia = models.CharField(blank=True, null=True)
    pv_agencia = models.CharField(blank=True, null=True)
    pv_codigo = models.AutoField(primary_key=True, null=False)
    pv_nombre = models.CharField(blank=True, null=True)
    pv_direcc = models.CharField()
    pv_siglas = models.CharField(blank=True, null=True)
    pv_pais = models.CharField(blank=True, null=True)
    pv_prvcia = models.CharField(blank=True, null=True)
    pv_actpro = models.CharField(blank=True, null=True)
    pv_region = models.CharField(blank=True, null=True)
    pv_telef1 = models.CharField(blank=True, null=True)
    pv_telef2 = models.CharField(blank=True, null=True)
    pv_fax = models.CharField(blank=True, null=True)
    pv_telex = models.CharField(blank=True, null=True)
    pv_contacto = models.CharField(blank=True, null=True)
    pv_refere1 = models.CharField(blank=True, null=True)
    pv_refere2 = models.CharField(blank=True, null=True)
    pv_tipo = models.CharField(blank=True, null=True)
    pv_moneda = models.CharField(blank=True, null=True)
    pv_person = models.CharField(blank=True, null=True)
    pv_cedruc = models.CharField(blank=True, null=True)
    pv_estado = models.CharField(blank=True, null=True)
    pv_fechoa = models.DateTimeField()
    pv_usera = models.CharField(blank=True, null=True)
    pv_fechoe = models.DateTimeField(blank=True, null=True)
    pv_usere = models.CharField(blank=True, null=True)
    pv_cta_aux = models.CharField(blank=True, null=True)
    pv_cta_dol = models.CharField(blank=True, null=True)
    pv_cup_suc = models.DecimalField(max_digits=12, decimal_places=2)
    pv_cup_dol = models.DecimalField(max_digits=12, decimal_places=2)
    pv_cupsuc_u = models.DecimalField(max_digits=12, decimal_places=2)
    pv_cupdol_u = models.DecimalField(max_digits=12, decimal_places=2)
    pv_contesp = models.CharField(blank=True, null=True)
    pv_codcob = models.IntegerField(blank=True, null=True)
    pv_numcalle = models.CharField(blank=True, null=True)
    pv_autimp = models.CharField(blank=True, null=True)
    pv_serie = models.CharField(blank=True, null=True)
    pv_aut_sri = models.CharField(blank=True, null=True)
    pv_codbanco = models.CharField(blank=True, null=True)
    pv_tipcta = models.CharField(blank=True, null=True)
    pv_cta = models.CharField(blank=True, null=True)
    pv_pago_aut = models.CharField(blank=True, null=True)
    pv_fecnac = models.DateField(blank=True, null=True)
    pv_mail = models.CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ciatt011'
        unique_together = (('pv_cia', 'pv_agencia', 'pv_codigo'),)
