"""
Django settings for ewsite project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
#ALLOWED_HOSTS = ['192.168.1.14', 'localhost', '127.0.0.1']
#CSRF_TRUSTED_ORIGINS = [
#    'https://192.168.1.14',
#    'http://localhost',
#    'http://127.0.0.1',
#]

DEBUG = os.getenv('DEBUG') == 'True'
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'menuprapp',
    'tallerapp',
    'comprasapp',
    'repuestosapp',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DynamicConnectionMiddleware',
]

ROOT_URLCONF = 'ewsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.company_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ewsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3'
    }
}

DATABASE_ROUTERS = ['core.routers.CompanyDBRouter']

_db_path = BASE_DIR / 'db.sqlite3'
if os.path.exists(_db_path):
    try:
        _conn = sqlite3.connect(_db_path)
        _cursor = _conn.execute(
            "SELECT db_alias, db_engine, db_dsn, db_name, db_server, db_host, db_port FROM core_company WHERE activa=1"
        )
        for _row in _cursor.fetchall():
            _alias, _engine, _dsn, _name, _server, _host, _port = _row

            if _engine == 'django_informixdb':
                DATABASES[_alias] = {
                    'ENGINE':   'django_informixdb',
                    'DSN':      _dsn,
                    'NAME':     _name,
                    'SERVER':   _server,
                    'HOST':     _host,
                    'USER':     '',
                    'PASSWORD': '',
                    'TEST':     {'NAME': None},
                    'OPTIONS':  {'MIGRATE': False},
                    'ATOMIC_REQUESTS': False,
                    'AUTOCOMMIT': True,
                    'CONN_MAX_AGE': 0,
                }
            else:
                # PostgreSQL, MySQL, Oracle, SQL Server
                DATABASES[_alias] = {
                    'ENGINE':   _engine,
                    'NAME':     _name,
                    'HOST':     _host,
                    'PORT':     _port or '',
                    'USER':     '',
                    'PASSWORD': '',
                    'TEST':     {'NAME': None},
                    'OPTIONS':  {'MIGRATE': False},
                    'ATOMIC_REQUESTS': False,
                    'AUTOCOMMIT': True,
                    'CONN_MAX_AGE': 0,
                }
        _conn.close()
    except Exception:
        pass

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
import os

STATIC_URL = '/static/'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
