# Generated by Django 5.2.13 on 2026-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyudaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_menu', models.CharField(max_length=50, unique=True, verbose_name='Código del menú')),
                ('modulo', models.CharField(max_length=80, verbose_name='Módulo')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo')),
                ('proceso', models.JSONField(blank=True, default=list, verbose_name='Proceso')),
                ('consejos', models.JSONField(blank=True, default=list, verbose_name='Recomendaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Ayuda de módulo',
                'verbose_name_plural': 'Ayudas de módulos',
                'db_table': 'config_ayuda_modulo',
                'ordering': ['modulo', 'titulo'],
            },
        ),
    ]
