# Generated by Django 5.2.13 on 2026-08-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayudamodulo',
            options={'ordering': ['modulo', 'titulo']},
        ),
    ]
